server:
  port: 8080

# Redis数据库索引（默认为0）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

logging:
  level:
    org.springframework: debug


